### ISSUE TITLE
Moodle 4.2.3: No sketch availabe in test for Essay question type

### ISSUE THREAD

**Issue by BearsBeetsBattlestarGalactica** [Syxton/moodle-tiny_sketch#8] opened 2023-12-06 13:53 UTC
Hello,

first of all, thank you for this useful plugin.

We noticed that there is no option to add a sketch when being in the TinyMCE Editor of an essay question:
![image](https://github.com/Syxton/moodle-tiny_sketch/assets/95363686/e6e43c87-66ec-4582-9af0-ecbc6507eab2)

A lot of our users might be confronted with a "Please explain or sketch" type of a question in an exam setting.

Is it possible to add the possibility of inserting a sketch for this question type? I know that there is an additional Sketch question type but since we want to give students the possibility to add sketches to their essay questions this is not exactly what we are looking for.

Thank you already,

Dominic

**Comment by slakky** [comment] 2024-01-11 09:00
Seems to be related/caused by [MDL-77812](https://tracker.moodle.org/browse/MDL-77812). A bug since Moodle 4.0 not allowing to upload media to the _Response template_ field of the question/essay, no matter of setting the **Response format** within the **Response options** to **HTML editor with file picker** of question/essay or not, making the following condition become false:
https://github.com/Syxton/moodle-tiny_sketch/blob/fb7e816b948bf0d337552ba0e929a8053090c43a/classes/plugininfo.php#L63

This line **also** causes tiny_sketch not being loaded by tiny within an essay question while **attempting** (not creating a Response template for) it. 
I did some investigation: Forcing this line to evaluate always to true (making the plugin always available in every WYSIWYG/tiny context) and creating a sketch within an attempt and storing the answer works; still fails within a _Response template_ storing (as said, related to MDL-77812).

**Comment by slakky** [comment] 2024-01-11 10:34
> Forcing this line to evaluate always to true (making the plugin always available in every WYSIWYG/tiny context)

Submitted https://github.com/Syxton/moodle-tiny_sketch/pull/9 with a proper evaluation. With the current patch from [MDL-77812](https://tracker.moodle.org/browse/MDL-77812) being merged this issue should be fixed.

**Comment by Syxton** [comment] 2024-09-04 16:56
Fixed via #9  Thank you @slakky

**Closed as completed by Syxton** 2024-09-04 16:56 UTC
